/**
 * UnifonicNextGenLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const Environments = {

    /**
     * Describe the setting where software and other products are actually put into operation for
     * their intended uses by end users
     */
    PRODUCTION: 'production',

};

module.exports = Environments;
