/**
 * UnifonicNextGenLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const SendResponse = require('../lib/Models/SendResponse');
const SendScheduledmessagesResponse = require('../lib/Models/SendScheduledmessagesResponse');
const StopScheduledMessagesResponse = require('../lib/Models/StopScheduledMessagesResponse');
const GetMessagesDetailsResponse = require('../lib/Models/GetMessagesDetailsResponse');
const SendWrapperResponse = require('../lib/Models/SendWrapperResponse');
const GetMessageQueryResponse = require('../lib/Models/GetMessageQueryResponse');
const GetScheduledMessageResponse = require('../lib/Models/GetScheduledMessageResponse');

const classMap = {
    SendResponse,
    SendScheduledmessagesResponse,
    StopScheduledMessagesResponse,
    GetMessagesDetailsResponse,
    SendWrapperResponse,
    GetMessageQueryResponse,
    GetScheduledMessageResponse,
};

/**
 * Factory class to create instances of models and exception classes
 */
class ModelFactory {
    /**
     * Creates instance of a model class
     * @param  modelName  {string}  Name of class to instantiate
     * @returns  {object} Instance of the model class
     */
    static getInstance(modelName) {
        return new classMap[modelName]();
    }
}

module.exports = ModelFactory;
